package service

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"

	"pijar/utils/model_util"

	"github.com/gin-gonic/gin"
)

// GenerateArticles generates articles based on provided preferences
func GenerateArticles(c *gin.Context, preferences []string) ([]*model_util.GeneratedArticle, error) {
	var result []*model_util.GeneratedArticle

	// Default to at least one preference if none provided
	if len(preferences) == 0 {
		preferences = []string{"teknologi"}
	}

	// Get topicID from context if available
	topicID, exists := c.Get("topic_id")
	if !exists {
		// Default to 1 if not provided
		topicID = 1
	}

	// Limit to max 2 articles for performance
	limit := len(preferences)
	if limit > 2 {
		limit = 2
	}

	for i := 0; i < limit; i++ {
		preference := preferences[i]

		fmt.Printf("🔍 Memproses preferensi: %s\n", preference)

		// Use the preference as both topic and preference, with the actual topicID
		article, err := GenerateArticleFromDeepseek(c, preference, preference, topicID.(int))
		if err != nil {
			fmt.Printf("❌ Gagal generate artikel untuk preferensi '%s': %v\n", preference, err)
			continue
		}

		result = append(result, article)
	}

	return result, nil
}

// GenerateArticleFromDeepseek generates a single article using the Deepseek API
func GenerateArticleFromDeepseek(c *gin.Context, topic string, preference string, topicID int) (*model_util.GeneratedArticle, error) {
	// Get API key from environment variable
	apiKey := os.Getenv("AI_API")
	if apiKey == "" {
		return nil, fmt.Errorf("AI_API environment variable is not set")
	}

	prompt := fmt.Sprintf(`Buat artikel tentang %s dengan format ketat:

		1. **Judul:** [1 judul informatif]
		2. **Isi:** 
   			- [minimal 300 kata, masing-masing 1 paragraf pendek]
   			- Setiap paragraf dipisahkan oleh baris baru
		3. **Sumber:** [1 referensi/sumber]
		4. **Preferensi:** [%s]`, topic, preference)

	reqBody := model_util.DeepseekChatRequest{
		Model: "deepseek-chat",
		Messages: []model_util.DeepseekChatMessage{
			{Role: "user", Content: prompt},
		},
	}

	jsonBody, err := json.Marshal(reqBody)
	if err != nil {
		return nil, fmt.Errorf("gagal encode JSON: %w", err)
	}

	req, err := http.NewRequest("POST", "https://api.deepseek.com/v1/chat/completions", bytes.NewBuffer(jsonBody))
	if err != nil {
		return nil, fmt.Errorf("gagal buat request: %w", err)
	}

	// Use API key from environment variable
	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("gagal kirim request: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("gagal baca response: %w", err)
	}

	var result model_util.DeepseekChatResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		fmt.Println("Respon mentah:\n", string(respBody))
		return nil, fmt.Errorf("gagal decode response JSON: %w", err)
	}

	if len(result.Choices) == 0 || result.Choices[0].Message.Content == "" {
		fmt.Println("Respon mentah:\n", string(respBody))
		return nil, fmt.Errorf("tidak ada hasil dari Deepseek")
	}

	content := result.Choices[0].Message.Content
	article := parseGeneratedArticle(content, topicID)

	return article, nil
}

func parseGeneratedArticle(raw string, topicID int) *model_util.GeneratedArticle {
	// Clean up the raw input
	raw = strings.TrimSpace(raw)
	if raw == "" {
		// Return default values if raw is empty
		return &model_util.GeneratedArticle{
			Title:   "Untitled Article",
			Content: "No content available",
			Source:  "Generated by AI",
			TopicID: topicID,
		}
	}

	lines := strings.Split(raw, "\n")

	var title, source string
	var contentLines []string

	// Try to extract title and source from markdown format
	for _, line := range lines {
		line = strings.TrimSpace(line)

		switch {
		case strings.HasPrefix(strings.ToLower(line), "**judul:"):
			title = strings.TrimSpace(strings.TrimPrefix(strings.ToLower(line), "**judul:"))
			title = strings.TrimSuffix(title, "**")
			title = strings.TrimSpace(title)

		case strings.HasPrefix(strings.ToLower(line), "**sumber:"):
			source = strings.TrimSpace(strings.TrimPrefix(strings.ToLower(line), "**sumber:"))
			source = strings.TrimSuffix(source, "**")
			source = strings.TrimSpace(source)

		case line != "" && !strings.HasPrefix(line, "**"):
			contentLines = append(contentLines, line)
		}
	}

	// If we couldn't find a title, use the first line of content
	if title == "" && len(contentLines) > 0 {
		title = contentLines[0]
		if len(contentLines) > 1 {
			contentLines = contentLines[1:]
		}
	} else if title == "" {
		title = "Untitled Article"
	}

	// If we have no content, use a default message
	content := strings.Join(contentLines, "\n")
	if content == "" {
		content = "No content available"
	}

	// If we have no source, use a default
	if source == "" {
		source = "Generated by AI"
	}

	return &model_util.GeneratedArticle{
		Title:   title,
		Content: content,
		Source:  source,
		TopicID: topicID,
	}
}
